# Site settings
title: Albert Bellonch
email: albert@bellonch.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bellonch.com" # the base hostname & protocol for your site
permalink: /:title
twitter_username: abellonch
github_username: albertbellonch

# Build settings
markdown: kramdown

# Assets
assets:
  js_compressor: uglifier
  css_compressor: yui

# Other
mode: production
